### ISSUE TITLE
Import from URL

### ISSUE THREAD

**Issue by samwilson** [Griboedow/PandocUltimateConverter#1]
I often want to import an HTML page (with images) from the web. Pandoc handles HTML→Wikitext (with many caveats of course, but it does work). Would this be a useful feature addition to this extension? I'd be happy to work on it.

**Comment by Griboedow** [comment]
Sounds like a good idea, would be glad to see a PR from you!


Regarding UI, we can have radiobuttons to choose the source, smth like:

== Source ==
( * )  Select file [Browse]
(   )  Specify URL: [____________]

==Target ==
Target page name: [____________]

**Comment by Griboedow** [comment]
Tried to take a look myself -- branch [convert-from-url](https://github.com/Griboedow/PandocUltimateConverter/tree/convert-from-url) 

![image](https://github.com/user-attachments/assets/d2ee4563-d693-48ec-b88f-1abc2d7cf5a4)


I am not sure why exactly, but pandoc cannot get URL when is running under php. Maybe some safety issue?

```
Could not fetch http://localhost/dashboard/
HttpExceptionRequest Request {
  host                 = "localhost"
  port                 = 80
  secure               = False
  requestHeaders       = [("User-Agent","\"Mozilla/5.0\"")]
  path                 = "/dashboard/"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 (ConnectionFailure user error (Network.Socket.gai_strerror not supported: 11003))

```

The thing is, that without that approach we would be forced to manually process file links and save them as file. And that will be much more work than I would like to see. 

Probably need to understand the reason why pandoc cannot get web data when called from php

**Comment by Griboedow** [comment]
I've added env variables to the shell call and looks like that resolved the issue. 

See #8 

I'm closing the issue. Documentationwill be updated as well.

**Comment by samwilson** [comment]
Thank you for this! It's a great feature. I've been using it a bit.
