### ISSUE TITLE
problems importing images in .emf format

### ISSUE THREAD

**Issue by perjes** [Griboedow/PandocUltimateConverter#6]
Hi!
¡Muchas gracias por tu extensión! :)
I faced with a problem importing .docx documents containing images in .emf format
Pandoс successfully pulls these pictures out of the document and saves them to the wiki database.
But mediawiki does not support the format and link like this appear in my article:
[File:Pandocultimateconverter-8cb75f65-0a0c-43d6-a101-ab514afcc0d0-image3.emf](http://10.2.97.44/last_of_us/index.php/%D0%A4%D0%B0%D0%B9%D0%BB:Pandocultimateconverter-8cb75f65-0a0c-43d6-a101-ab514afcc0d0-image3.emf)
Is it possible to force Pandoс to change the format of such files to .png
and/or prohibit writing unsupported files to the wiki?

I'm attaching the logs
[misc.log](https://github.com/user-attachments/files/15886026/misc.log)
[main.log](https://github.com/user-attach
[test emf page.docx](https://github.com/user-attachments/files/15886059/test.emf.page.docx)
ments/files/15886030/main.log)

**Comment by Griboedow** [comment]
Probably we can't do much with conversion (it will require one more tool)

I lean towards adding a config with an array of extensions to skip from upload.

**Comment by Griboedow** [comment]
I've supported config
`$wgPandocUltimateConverter_MediaFileExtensionsToSkip = [ 'emf' ];`

By default it contains EMF

For now, I did not cleanup in postprocessing (it might be helpful to at least know some files are not processed).

![image](https://github.com/Griboedow/PandocUltimateConverter/assets/4194526/c5f1e892-57b6-4f5f-8037-e1b5118c7d61)

Later on, we may add an additional param (false by default) to cleanup such redlinks.

**Comment by perjes** [comment]
Hello, unfortunately the new fix only works on a test file.
When i'm trying to download a larger file, multiple errors occur in the browser:
Warning: strtolower() expects parameter 1 to be string, array given in /var/www/html/last_of_us/extensions/PandocUltimateConverter/includes/PandocWrapper.php on line 82
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/last_of_us/extensions/PandocUltimateConverter/includes/PandocWrapper.php:82) in /var/www/html/last_of_us/extensions/PandocUltimateConverter/includes/SpecialPandocUltimateConverter.php on line 83
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/last_of_us/extensions/PandocUltimateConverter/includes/PandocWrapper.php:82) in /var/www/html/last_of_us/includes/WebResponse.php on line 75
I am also attaching the logs.
[misc.log](https://github.com/user-attachments/files/16052996/misc.log)
[main.log](https://github.com/user-attachments/files/16052997/main.log)

**Comment by Griboedow** [comment]
```
[error] [ee067b6119a7a20f2af24dfb] /last_of_us/index.php/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:PandocUltimateConverter   PHP Warning: strtolower() expects parameter 1 to be string, array given
#0 [internal function]: MWExceptionHandler::handleError()
#1 [internal function]: strtolower()
#2 /var/www/html/last_of_us/extensions/PandocUltimateConverter/includes/PandocWrapper.php(82): array_map()
```

The code is:
```
$mediaFilesExtensionsToSkip = $config->get( 'PandocUltimateConverter_MediaFileExtensionsToSkip' ) ?? []; 
<..>
in_array(strtolower($extension), array_map('strtolower', $mediaFilesExtensionsToSkip))
```

How is your `PandocUltimateConverter_MediaFileExtensionsToSkip` variable specified? 

It should be array of strings. **Might it be that you've added array as an element of this array?** For example, smth like
`$PandocUltimateConverter_MediaFileExtensionsToSkip[] = ['my_extension']`
?

**Comment by perjes** [comment]
Hello!
The problem occurs regardless of the key $wgPandocUltimateConverter_MediaFileExtensionsToSkip
when log collection is enabled
Here is my config file:

#PandocUltimateConverter
wfLoadExtension( 'PandocUltimateConverter' );
$wgPandocExecutablePath = '/bin/pandoc';
$wgPandocTmpFolderPath = '/tmp/pandoc';
$wgFileExtensions[] = 'docx';
$wgFileExtensions[] = 'odt';
#$wgPandocUltimateConverter_MediaFileExtensionsToSkip = [ 'emf' ];

error_reporting( -1 );
$wgDebugLogFile = "/var/log/mediawiki/$wgDBname/main.log";
$wgDebugLogPrefix = date( '[Y-m-d H:i:s] ' );
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
error_reporting( E_ALL ); ini_set( 'display_errors', 1 );

$wgDebugLogGroups['DBQuery'] =
$wgDebugLogGroups['DBReplication'] =
$wgDebugLogGroups['DBConnection'] =
$wgDebugLogGroups['runJobs'] =
$wgDebugLogGroups['Parsoid'] =
$wgDebugLogGroups['rdbms'] = "/var/log/mediawiki/$wgDBname/misc.log";

**Comment by Griboedow** [comment]
Interesting! 
So far I was not able to reproduce it. Is it possible to create a sample docx file to confirm the issue?

**Comment by perjes** [comment]
> Interesting! So far I was not able to reproduce it. Is it possible to create a sample docx file to confirm the issue?

Hello! I sent the document via private message

**Comment by Griboedow** [comment]
Thanks!

I didn't find out what was the reason of the issue, but I made a stupid fix for it. Should work now :)

**Comment by Griboedow** [comment]
Found out the reason, it was related to the fact that I'm using "configs" from manifest v2, but manifest version is v1 in extension.json

Made a proper fix. 

Manifest v2 works for MW 1.29+. so that's not a big deal.

**Comment by perjes** [comment]
it looks like that works correctly
Thanks!

> Found out the reason, it was related to the fact that I'm using "configs" from manifest v2, but manifest version is v1 in extension.json
> 
> Made a proper fix.
> 
> Manifest v2 works for MW 1.29+. so that's not a big deal.
