### ISSUE TITLE
right to use the plugin 

### ISSUE THREAD

**Issue by perjes** [Griboedow/PandocUltimateConverter#9]
Hello!
as it turned out, some authors with editor rights are overusing the capabilities of this excellent plugin.
Is it possible to set the right to use the plugin only for a certain group?

**Comment by Griboedow** [comment]
Currently custom permissions are not supported, but it makes sense to support group-based permissions

**Comment by Griboedow** [comment]
I've added a config 

You can check it, for example, with `$wgPandocUltimateConverter_PandocCustomUserRight` to support list from here: https://www.mediawiki.org/wiki/Manual:User_rights

You can try it with
`$wgPandocUltimateConverter_PandocCustomUserRight = 'nominornewtalk';`
Looks like, that's typically a bot permission, so it should show "Permission denied" if you open the page as a normal user

**Comment by perjes** [comment]
if I understood your idea correctly, you propose to bind the right to use the extension to one of the system rights, in this case one of the rights of the bot group.
I realized that I don't want to give bot rights to my editors and made a new group with a single right - 'nominornewtalk'
```
$wgPandocUltimateConverter_PandocCustomUserRight = 'nominornewtalk';
$wgGroupPermissions['pandoc-import']['nominornewtalk'] = true;
```

and it works, thanks!

**Comment by Griboedow** [comment]
Yep, exactly! Bot rights were just for an example.

Glad it worked for you!
